name: Super Tropical
favicon: null
layout_spectrum: 0.9947740859352052
typography_spectrum: 0.31024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e0dc'
    - '#3e8da7'
    - '#3b2121'
    - '#d95b8f'
    - '#8cd083'
  brandStrength: 0.9223294830881059
  lightness: 0.6153289373032749
  saturation: 0.580215873895213
  rhythmicContrast: 0.4539213178213686
purpose: []
